;       *
;    Filename: SEMAFORO PROJETO INTEGRADOR UNIVESP *
;    Date:   24/05/2020                                                                  *
;    File Version:   1.0                                                          *
;    Author:      ALUNOS BIMESTRE 10 UNIVESP                                                             *
;    Company:    UNIVESP                                                              *
;    Description:  PROJETO QUE VISA A MELHORIA NO AMBIENTE COVID19
;    *
;                                                                              *
;*******************************************************************************
    list  p=pic16f628a
    #include <p16f628a.inc>
   
 ;;;;;-----config dos fuse bits-------
    __CONFIG _FOSC_INTOSCCLK & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF    
    #define BANK1 bsf STATUS,RP0
    #define BANK0 bcf STATUS,RP0
    #define        RS  PORTB,RB0

;*******************************************************************************
; Reset Vector
;*******************************************************************************
MY_VARIABLES UDATA
COPY_NUM1   RES 1
CENTENA RES 1 ;;;;;ARMAZENA RESUTADO LOW BYTE
DEZENA RES 1 ;;;;;ARMAZENA RESUTADO LOW BYTE
UNIDADE RES 1 ;;;;;ARMAZENA RESUTADO LOW BYTE
CHAR_SWAP    res     1 ; ;;;VARIAVEIS SE EU PRECISAR
NUM1 RES 1 ;;;;;PRIMEIRO NUMERO MULTIPLICADO
NUM2 RES 1 ;;;;;SEGUNDO NUMERO MULTIPLICADO
AUX RES 1 ;;;;;ARMAZENA RESUTADO LOW BYTE
AUX2 RES 1 ;;;;;ARMAZENA RESUTADO LOW BYTE
DCONTADOR1  RES 1
DCONTADOR2  RES 1
DCONTADOR3  RES 1
VALOR  RES 1  
CONT RES 1  

   

   
     
RES_VECT  CODE    0x0000            ; processor RESet vector
    BANK1
    CLRF TRISB ; CONFIGURAÇÃO DO PORT B COMO SAIDA PIN IO
    MOVLW   B'00000011'
    MOVWF   TRISA ; CONFIGURAÇÃO DO PORT RA0,RA1 COMO ENTRADAS E RA2,3,4 COMO SAIDAS
    BANK0
    GOTO MAIN
;;;;;;;INICIO INICIAR LCD;;;;;;;;;;;;;;;;
MAIN:
    CLRF PORTB ; SETANDO PORTB PARA  "0000000"
    CALL INICIALIZA_LCD ;;;CHAMA INICOLAIALIZA LCD
    CALL INICIO
    ;------INICIO ---------
INICIO:
MOVLW D'1';;;;;CARREGA O NUMERO EM W
  MOVWF NUM1
MOVWF NUM1
MOVWF COPY_NUM1
  CALL CONTAGEM

; --- ROTINAS AUXILIARES DESENVOLVIMENTO ---
CONTAGEM:
CALL COMPARA
BTFSS PORTA,RA0
CALL INCREMENTA
BTFSS PORTA,RA1
CALL DECREMENTA
GOTO CONTAGEM
INCREMENTA:
CALL RETARDO_10MS
CALL EXIBE_VAR
CALL RETARDO_10MS
BTFSC PORTA,RA0
    INCF NUM1
CALL DIV
RETURN
DECREMENTA:

CALL RETARDO_10MS
CALL EXIBE_VAR
CALL RETARDO_10MS
BTFSC PORTA,RA1
    DECFSZ NUM1
GOTO $+3
GOTO $+1
GOTO ZERA
CALL DIV
RETURN
ZERA:
    NOP
    GOTO    INICIO
COMPARA:
       MOVLW .5
       MOVWF VALOR    ;;;N1  
       SUBWF    NUM1,W ;;;N2
       BTFSC    STATUS,Z ;;;;USA O REGISTRADOR STATUS Z QUE COMPARA RESULTADO
       GOTO     AMARELO
       BTFSS    STATUS,C
       GOTO     VERDE
       GOTO     VERMELHO
       RETURN
AMARELO:
    BSF PORTA,RA2 ;;VERMELHO    
    BCF PORTA,RA3
    BSF PORTA,RA4
      RETURN  
VERDE:
    BSF PORTA,RA3
    BCF PORTA,RA2
    BSF PORTA,RA4
    RETURN
VERMELHO:
    BSF  PORTA,RA2
    MOVLW .10
    MOVWF VALOR    ;;;N1  
    SUBWF    NUM1,W ;;;N2
    BTFSC    STATUS,Z ;;;;USA O REGISTRADOR STATUS Z QUE COMPARA RESULTADO
    GOTO    $ +2    
    GOTO    $ +3
    BCF PORTA,RA4 ;;;;É OPEN DRAIN OU COLETOR ABERTO
    BCF PORTA,RA3
    BCF PORTA,RA2
    RETURN

DIV:
CLRF CENTENA ;;;;;;LIMPA O REGISTRADOR PARA INICIAR OPERAÇOES
CLRF DEZENA ;;;;;;LIMPA O REGISTRADOR PARA INICIAR OPERAÇOES
CLRF UNIDADE ;;;;;;LIMPA O REGISTRADOR PARA INICIAR OPERAÇOES
DIV_100:
MOVF NUM1,W ;;;;ESTA AQUI É PARA GUARDAR VALOR SE OCORRER CARRY
MOVWF COPY_NUM1
MOVF NUM1,W ;;;;ESTA AQUI É PARA GUARDAR VALOR SE OCORRER CARRY
MOVWF AUX ;;;;CONSERVA AQUI NESTA
      MOVLW D'100'
  MOVWF NUM2
MOVF NUM2,W ;COPIA DIVISOR PARA O W
SUBWF NUM1,F ;;;;SUBTRAI DIVISOR NUM1  DO DIVIDENDO NUM2
BTFSS STATUS,C; ;;;;;TESTA PARA VER SE HOUVE CARRY
GOTO DIV_10;;;;;;DIVISOR MENOR QUE ZERO DESVIA
INCF CENTENA,F;;;;SE DIVIDENDO MAIOR QUE ZERO INCREMENTA
MOVF NUM1,W ;COPIA DIVISOR PARA O W
MOVWF AUX
GOTO DIV_100;;;;;RETORNA EFAZ MAIS SUBRACOES
DIV_10:
MOVF AUX,W
MOVWF AUX2
MOVLW D'10'
  MOVWF NUM2
SUBWF AUX,F ;;;;SUBTRAI DIVISOR NUM1  DO DIVIDENDO NUM2
BTFSS STATUS,C; ;;;;;TESTA PARA VER SE HOUVE CARRY
GOTO DIV_1;;;;;;DIVISOR MENOR QUE ZERO DESVIA
INCF DEZENA,F;;;;SE DIVIDENDO MAIOR QUE ZERO INCREMENTA
MOVF AUX,W ;COPIA DIVISOR PARA O W
MOVWF AUX2
GOTO DIV_10;;;;;RETORNA EFAZ MAIS SUBRACOES
DIV_1:
MOVLW D'1'
  MOVWF NUM2
SUBWF AUX2,F ;;;;SUBTRAI DIVISOR NUM1  DO DIVIDENDO NUM2
BTFSS STATUS,C; ;;;;;TESTA PARA VER SE HOUVE CARRY
GOTO RESTABELECE_NUM1;;;;;;DIVISOR MENOR QUE ZERO DESVIA
INCF UNIDADE,F;;;;SE DIVIDENDO MAIOR QUE ZERO INCREMENTA
MOVF AUX2,W ;COPIA DIVISOR PARA O W
MOVWF AUX2
GOTO DIV_1;;;;;RETORNA EFAZ MAIS SUBRACOES

RESTABELECE_NUM1:
MOVF COPY_NUM1,W ;;;;ESTA AQUI É PARA GUARDAR VALOR SE OCORRER CARRY
MOVWF NUM1
RETURN

INICIALIZA_LCD:
    MOVLW B'00110000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS

    MOVLW B'00110000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS

    MOVLW B'00110000';;;;3 x B'0011
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS

    MOVLW B'00100000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS

    MOVLW B'00100000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS

    MOVLW B'10000000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS

    MOVLW B'00000000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS

    MOVLW B'11110000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS
    RETURN
   
ENABLE:  ;;;;FUNCAO DE COMANDO HABILITA
    BSF PORTB,RB1 ; E HABILITA COMANDO
    NOP
    BCF PORTB,RB1 ; E HABILITA COMANDO
    RETURN  
   
LINHA_1:
    MOVLW B'10000000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS

    MOVLW B'00000000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS
    RETURN
   

LINHA_2:
    MOVLW B'11000000'
    MOVWF   PORTB
    CALL ENABLE
    MOVLW B'00000000'
    MOVWF   PORTB
    CALL ENABLE
    CALL RETARDO_1MS
    RETURN
   
       
   
PRINTCHAR:
    MOVWF  CHAR_SWAP
    MOVWF   PORTB
    BSF RS
    CALL ENABLE
    CALL RETARDO_1MS

    SWAPF   CHAR_SWAP
    MOVF   CHAR_SWAP,W
    MOVWF   PORTB
    BSF RS
    CALL ENABLE
    CALL RETARDO_1MS
    BCF RS
    RETURN    
   
EXIBE_VAR:
    CALL LINHA_2
    MOVLW   .48
    ADDWF    CENTENA,W
    CALL PRINTCHAR
   
    MOVLW   .48
    ADDWF    DEZENA,W
    CALL PRINTCHAR

   
    MOVLW   .48
    ADDWF    UNIDADE,W
    CALL PRINTCHAR
    RETURN  
   
RETARDO_1MS:
    MOVLW D'73'
    MOVWF DCONTADOR1
    MOVLW D'2'
    MOVWF DCONTADOR2    
LOOP_DELAY_1MS:
    DECFSZ DCONTADOR1, 1
    GOTO LOOP_DELAY_1MS
    DECFSZ DCONTADOR2, 1
    GOTO LOOP_DELAY_1MS
    NOP
    NOP
    RETURN
   
RETARDO_10MS:
    MOVLW D'250'
    MOVWF DCONTADOR1
    MOVLW D'13'
    MOVWF DCONTADOR2
LOOP_DELAY_10MS:
    DECFSZ DCONTADOR1, 1
    GOTO LOOP_DELAY_10MS
    DECFSZ DCONTADOR2, 1
    GOTO LOOP_DELAY_10MS    
   
RETARDO_100MS:
    MOVLW D'220'
    MOVWF DCONTADOR1
    MOVLW D'130'
    MOVWF DCONTADOR2    
LOOP_DELAY_100MS:
    DECFSZ DCONTADOR1, 1
    GOTO LOOP_DELAY_100MS
    DECFSZ DCONTADOR2, 1
    GOTO LOOP_DELAY_100MS
    NOP
    RETURN    

RETARDO_500MS:
    MOVLW D'84'
    MOVWF DCONTADOR1
    MOVLW D'138'
    MOVWF DCONTADOR2
    MOVLW D'3'
    MOVWF DCONTADOR3
LOOP_DELAY_500MS:
    DECFSZ DCONTADOR1,1
    GOTO LOOP_DELAY_500MS
    DECFSZ DCONTADOR2,1
    GOTO LOOP_DELAY_500MS
    DECFSZ DCONTADOR3,1
    GOTO LOOP_DELAY_500MS
    NOP
    RETURN    
   
RETARDO_1S:
    MOVLW D'12'
    MOVWF DCONTADOR1
    MOVLW D'13'
    MOVWF DCONTADOR2
    MOVLW D'14'
    MOVWF DCONTADOR3
LOOP_DELAY_1S:
    DECFSZ DCONTADOR1,1
    GOTO LOOP_DELAY_1S
    DECFSZ DCONTADOR2,1
    GOTO LOOP_DELAY_1S
    DECFSZ DCONTADOR3,1
    GOTO LOOP_DELAY_1S
    NOP
    RETURN
   
MENSAGEM1:
    ADDWF   PCL,F
    DT "PROJETO PI 9BIM"
VISUALIZA1:
    MOVF    CONT,W
    CALL    MENSAGEM1
    CALL    PRINTCHAR
    INCF    CONT,F
    MOVLW   .15  ;;;NUMERO DE LETRAS DA PALAVRA QUE QUERO EXIBIR
    XORWF   CONT,W
    BTFSS   STATUS,Z
    GOTO  VISUALIZA1  ;;;Z=0  XOR=0  CONT =15
    CLRF    CONT ;;;ZERO CONTADOR PARA USAR EM OUTRAS MENSAGENS
    RETURN  ;;;;;Z=1   XOR=0  CONT =16
   
   
MENSAGEM2:
    ADDWF   PCL,F
    DT "SEMAFORO BANHEIR"
VISUALIZA2:
    MOVF    CONT,W
    CALL    MENSAGEM2
    CALL    PRINTCHAR
    INCF    CONT,F
    MOVLW   .16  ;;;NUMERO DE LETRAS DA PALAVRA QUE QUERO EXIBIR
    XORWF   CONT,W
    BTFSS   STATUS,Z
    GOTO  VISUALIZA2  ;;;Z=0  XOR=0  CONT =15
    CLRF    CONT ;;;ZERO CONTADOR PARA USAR EM OUTRAS MENSAGENS
    RETURN  ;;;;;Z=1   XOR=0  CONT =16        

END ;;;;FIM
